export declare const enum Descriptor_Type {
    DEVICE = 1,
    CONFIGURATION = 2,
    STRING = 3,
    INTERFACE = 4,
    ENDPOINT = 5,
    INTERFACE_POWER = 8,
    OTG = 9,
    DEBUG = 10,
    INTERFACE_ASSOCIATION = 11,
    BOS = 15,
    DEVICE_CAPABILITY = 16,
}
export declare const enum Request_Type {
    GET_STATUS = 0,
    CLEAR_FEATURE = 1,
    SET_FEATURE = 3,
    SET_ADDRESS = 5,
    GET_DESCRIPTOR = 6,
    SET_DESCRIPTOR = 7,
    GET_CONFIGURATION = 8,
    SET_CONFIGURATION = 9,
    GET_INTERFACE = 10,
    SET_INTERFACE = 11,
}
export declare const enum Capability_Type {
    Wireless_USB = 1,
    USB_2_0_Extension = 2,
    SUPERSPEED_USB = 3,
    CONTAINER_ID = 4,
    PLATFORM = 5,
    POWER_DELIVERY_CAPABILITY = 6,
    BATTERY_INFO_CAPABILITY = 7,
    PD_CONSUMER_PORT_CAPABILITY = 8,
    PD_PROVIDER_PORT_CAPABILITY = 9,
    SUPERSPEED_PLUS = 10,
    PRECISION_TIME_MEASUREMENT = 11,
    Wireless_USB_Ext = 12,
}
